"""迁移脚本

Revision ID: 2d894554dba2
Revises: 29ad0bc01075
Create Date: 2026-05-10 11:43:27.219339

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d894554dba2'
down_revision: str | None = '29ad0bc01075'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('consultation_compliance_diagnosis', 'compliance_score',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               comment='合规评分(0-10)',
               existing_comment='合规评分(0-100)',
               existing_nullable=False)
    op.alter_column('consultation_compliance_diagnosis', 'compliance_level',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               comment='合规等级(A/B/C/D)',
               existing_comment='合规等级(low/medium/high)',
               existing_nullable=False)
    op.add_column('consultation_info', sa.Column('longitude', sa.Float(), nullable=True, comment='经度'))
    op.add_column('consultation_info', sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'))
    op.add_column('consultation_info', sa.Column('venue_name', sa.String(length=200), nullable=True, comment='场馆名称'))
    op.add_column('consultation_info', sa.Column('fee_description', sa.Text(), nullable=True, comment='费用说明'))
    op.add_column('consultation_info', sa.Column('co_organizers', sa.JSON(), nullable=True, comment='协办方列表'))
    op.add_column('consultation_info', sa.Column('risk_factors', sa.JSON(), nullable=True, comment='风险因素列表'))
    op.add_column('consultation_info', sa.Column('is_archived', sa.Boolean(), nullable=False, comment='是否归档'))
    op.add_column('consultation_info', sa.Column('archived_time', sa.DateTime(), nullable=True, comment='归档时间'))
    op.add_column('consultation_info', sa.Column('archived_by', sa.BIGINT(), nullable=True, comment='归档人ID'))
    op.add_column('consultation_info', sa.Column('is_duplicate', sa.Boolean(), nullable=False, comment='是否为重复记录'))
    op.add_column('consultation_info', sa.Column('duplicate_of_id', sa.BIGINT(), nullable=True, comment='关联的原始记录ID'))
    op.add_column('consultation_info', sa.Column('search_keywords', sa.String(length=500), nullable=True, comment='搜索关键词'))
    op.add_column('consultation_info', sa.Column('crawl_url', sa.String(length=500), nullable=True, comment='抓取来源URL'))
    op.add_column('consultation_info', sa.Column('crawl_time', sa.DateTime(), nullable=True, comment='抓取时间'))
    op.add_column('consultation_info', sa.Column('external_id', sa.String(length=100), nullable=True, comment='外部系统ID(用于去重)'))
    op.alter_column('consultation_info', 'compliance_score',
               existing_type=mysql.INTEGER(),
               comment='合规评分(0-10)',
               existing_comment='合规评分(0-100)',
               existing_nullable=True)
    op.alter_column('consultation_info', 'compliance_level',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=10),
               comment='合规等级(A/B/C/D)',
               existing_comment='合规等级(low/medium/high)',
               existing_nullable=True)
    op.alter_column('consultation_info', 'updated_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.add_column('consultation_itinerary', sa.Column('consultation_ids', sa.JSON(), nullable=True, comment='关联咨询会ID列表'))
    op.add_column('consultation_itinerary', sa.Column('consultation_details', sa.JSON(), nullable=True, comment='关联咨询会详情列表'))
    op.add_column('consultation_itinerary', sa.Column('reminder_sent', sa.Boolean(), nullable=False, comment='是否已发送行程提醒'))
    op.alter_column('consultation_itinerary', 'updated_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.add_column('consultation_registration', sa.Column('team_id', sa.BIGINT(), nullable=True, comment='关联招生组ID'))
    op.add_column('consultation_registration', sa.Column('forwarded', sa.Boolean(), nullable=False, comment='是否已转发招生组'))
    op.add_column('consultation_registration', sa.Column('forwarded_time', sa.DateTime(), nullable=True, comment='转发时间'))
    op.alter_column('consultation_registration', 'updated_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否主键',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否查询字段',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否主键',
               existing_nullable=False)
    op.alter_column('consultation_registration', 'updated_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_column('consultation_registration', 'forwarded_time')
    op.drop_column('consultation_registration', 'forwarded')
    op.drop_column('consultation_registration', 'team_id')
    op.alter_column('consultation_itinerary', 'updated_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_column('consultation_itinerary', 'reminder_sent')
    op.drop_column('consultation_itinerary', 'consultation_details')
    op.drop_column('consultation_itinerary', 'consultation_ids')
    op.alter_column('consultation_info', 'updated_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('consultation_info', 'compliance_level',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='合规等级(low/medium/high)',
               existing_comment='合规等级(A/B/C/D)',
               existing_nullable=True)
    op.alter_column('consultation_info', 'compliance_score',
               existing_type=mysql.INTEGER(),
               comment='合规评分(0-100)',
               existing_comment='合规评分(0-10)',
               existing_nullable=True)
    op.drop_column('consultation_info', 'external_id')
    op.drop_column('consultation_info', 'crawl_time')
    op.drop_column('consultation_info', 'crawl_url')
    op.drop_column('consultation_info', 'search_keywords')
    op.drop_column('consultation_info', 'duplicate_of_id')
    op.drop_column('consultation_info', 'is_duplicate')
    op.drop_column('consultation_info', 'archived_by')
    op.drop_column('consultation_info', 'archived_time')
    op.drop_column('consultation_info', 'is_archived')
    op.drop_column('consultation_info', 'risk_factors')
    op.drop_column('consultation_info', 'co_organizers')
    op.drop_column('consultation_info', 'fee_description')
    op.drop_column('consultation_info', 'venue_name')
    op.drop_column('consultation_info', 'latitude')
    op.drop_column('consultation_info', 'longitude')
    op.alter_column('consultation_compliance_diagnosis', 'compliance_level',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               comment='合规等级(low/medium/high)',
               existing_comment='合规等级(A/B/C/D)',
               existing_nullable=False)
    op.alter_column('consultation_compliance_diagnosis', 'compliance_score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               comment='合规评分(0-100)',
               existing_comment='合规评分(0-10)',
               existing_nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
